package progra2proy1;

import progra2proy1.*;
import static java.lang.Integer.parseInt;
import java.util.ArrayList;
import javax.swing.JOptionPane;

public class EditarProducto2 extends javax.swing.JFrame {

    public String sucursal = "";
    public int editando = 0;
    Producto analisis = new Producto();
    Ingrediente ingrediente = new Ingrediente();
    Listas lista = new Listas();
    String ID;
    
    public EditarProducto2(String Sucursal, int Editando) {
        initComponents();
        sucursal = Sucursal;
        editando = Editando;
        lblTitulo.setText("Crear producto - " + Sucursal);
        if (Sucursal.equals("San Pedro")) {
            ID = lista.ObtenerListaProductos().get(editando).getIDProd();
        } else if (Sucursal.equals("Los Yoses")) {
            ID = lista.ObtenerListaProductos().get(editando).getIDProd();
        } else {
            ID = lista.ObtenerListaProductos().get(editando).getIDProd();
        }
        txtID.setText("ID para el producto: " + ID);
        CargarInformacion();
    }
    
    public void CargarInformacion() {
        
        txbNombre.setText(lista.ObtenerListaProductos().get(editando).getNombre());
        txtID.setText("ID para el producto: " + lista.ObtenerListaProductos().get(editando).getIDProd());
        
    }
    
    public Producto AnalizarIngredientes() {
        
        int ingr;
        ArrayList ingredientes = new ArrayList<>();
        
        if (chbIngr00.isSelected()) {
            ingr = 0;
            ingredientes.add(ingr);
        }
        if (chbIngr01.isSelected()) {
            ingr = 1;
            ingredientes.add(ingr);
        }
        if (chbIngr02.isSelected()) {
            ingr = 2;
            ingredientes.add(ingr);
        }
        if (chbIngr03.isSelected()) {
            ingr = 3;
            ingredientes.add(ingr);
        }
        if (chbIngr04.isSelected()) {
            ingr = 4;
            ingredientes.add(ingr);
        }
        if (chbIngr05.isSelected()) {
            ingr = 5;
            ingredientes.add(ingr);
        }
        if (chbIngr06.isSelected()) {
            ingr = 6;
            ingredientes.add(ingr);
        }
        if (chbIngr07.isSelected()) {
            ingr = 7;
            ingredientes.add(ingr);
        }
        if (chbIngr08.isSelected()) {
            ingr = 8;
            ingredientes.add(ingr);
        }
        if (chbIngr09.isSelected()) {
            ingr = 9;
            ingredientes.add(ingr);
        }
        if (chbIngr10.isSelected()) {
            ingr = 10;
            ingredientes.add(ingr);
        }
        if (chbIngr11.isSelected()) {
            ingr = 11;
            ingredientes.add(ingr);
        }
        if (chbIngr12.isSelected()) {
            ingr = 12;
            ingredientes.add(ingr);
        }
        if (chbIngr13.isSelected()) {
            ingr = 13;
            ingredientes.add(ingr);
        }
        if (chbIngr14.isSelected()) {
            ingr = 14;
            ingredientes.add(ingr);
        }
        if (chbIngr15.isSelected()) {
            ingr = 15;
            ingredientes.add(ingr);
        }
        if (chbIngr16.isSelected()) {
            ingr = 16;
            ingredientes.add(ingr);
        }
        if (chbIngr17.isSelected()) {
            ingr = 17;
            ingredientes.add(ingr);
        }
        if (chbIngr18.isSelected()) {
            ingr = 18;
            ingredientes.add(ingr);
        }
        if (chbIngr19.isSelected()) {
            ingr = 19;
            ingredientes.add(ingr);
        }
        
        analisis.setLista(ingredientes);
        
        return analisis;
    }
    
    public int AnalizarPrecio() {
        
        int precio = 0;
        String variable;
        
        for (int i = 0; i < analisis.getLista().size(); i++) {
            variable = analisis.getLista().get(i).toString();
            precio = precio + lista.ObtenerListaIngredientes().get(parseInt(variable)).getPrecio();
        }
        
        precio = (int) (precio * 1.25);
        
        return precio;
    }
    
    public ArrayList ListarIngredientes() {
        
        ArrayList listaIng = new ArrayList();
        String nombreIng = "";
        int precioIng = 0;
        
        for (int i = 0; i < analisis.getLista().size(); i++) {
            ingrediente.setNombre(lista.ObtenerListaIngredientes().get(i).getNombre());
            ingrediente.setPrecio(lista.ObtenerListaIngredientes().get(i).getPrecio());
            listaIng.add(ingrediente);
        }
        
        return listaIng;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtNombre = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        lblCrear = new javax.swing.JButton();
        lblVolver = new javax.swing.JButton();
        lblExplicacion = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        txtID = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txbNombre = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        chbIngr00 = new javax.swing.JCheckBox();
        chbIngr01 = new javax.swing.JCheckBox();
        chbIngr03 = new javax.swing.JCheckBox();
        chbIngr02 = new javax.swing.JCheckBox();
        chbIngr07 = new javax.swing.JCheckBox();
        chbIngr06 = new javax.swing.JCheckBox();
        chbIngr04 = new javax.swing.JCheckBox();
        chbIngr05 = new javax.swing.JCheckBox();
        chbIngr09 = new javax.swing.JCheckBox();
        chbIngr08 = new javax.swing.JCheckBox();
        chbIngr19 = new javax.swing.JCheckBox();
        chbIngr18 = new javax.swing.JCheckBox();
        chbIngr10 = new javax.swing.JCheckBox();
        chbIngr11 = new javax.swing.JCheckBox();
        chbIngr12 = new javax.swing.JCheckBox();
        chbIngr13 = new javax.swing.JCheckBox();
        chbIngr14 = new javax.swing.JCheckBox();
        chbIngr15 = new javax.swing.JCheckBox();
        chbIngr16 = new javax.swing.JCheckBox();
        chbIngr17 = new javax.swing.JCheckBox();
        jSeparator2 = new javax.swing.JSeparator();
        lblPrecio = new javax.swing.JLabel();
        btnPrecio = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(480, 620));
        setResizable(false);

        txtNombre.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtNombre.setMaximumSize(new java.awt.Dimension(400, 600));
        txtNombre.setMinimumSize(new java.awt.Dimension(400, 600));
        txtNombre.setPreferredSize(new java.awt.Dimension(400, 600));

        lblTitulo.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        lblTitulo.setText("Crear producto - SUCURSAL");

        lblCrear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/progra2proy1/imagenes/pencilG.png"))); // NOI18N
        lblCrear.setText(" Editar producto");
        lblCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lblCrearActionPerformed(evt);
            }
        });

        lblVolver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/progra2proy1/imagenes/volver.png"))); // NOI18N
        lblVolver.setText(" Menú anterior");
        lblVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lblVolverActionPerformed(evt);
            }
        });

        lblExplicacion.setText("Puede crear un producto a continuación. Debe indicar un nombre y al");

        jLabel1.setText("menos dos ingredientes.");

        txtID.setText("ID para el producto:");

        jLabel3.setText("Nombre del producto:");

        txbNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txbNombreActionPerformed(evt);
            }
        });

        jLabel4.setText("Seleccione los ingredientes:");

        chbIngr00.setText("00 Torta de carne: ₡ 400");
        chbIngr00.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chbIngr00ActionPerformed(evt);
            }
        });

        chbIngr01.setText("01 Salchicha: ₡ 200");
        chbIngr01.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chbIngr01ActionPerformed(evt);
            }
        });

        chbIngr03.setText("03 Pan de Hot Dog: ₡ 125");
        chbIngr03.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chbIngr03ActionPerformed(evt);
            }
        });

        chbIngr02.setText("02 Pan de hamburguesa: ₡ 150");
        chbIngr02.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chbIngr02ActionPerformed(evt);
            }
        });

        chbIngr07.setText("07 Cebolla: ₡ 150");
        chbIngr07.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chbIngr07ActionPerformed(evt);
            }
        });

        chbIngr06.setText("06 Tomate: ₡ 150");
        chbIngr06.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chbIngr06ActionPerformed(evt);
            }
        });

        chbIngr04.setText("04 Repollo: ₡ 100");
        chbIngr04.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chbIngr04ActionPerformed(evt);
            }
        });

        chbIngr05.setText("05 Lechuga: ₡ 80");
        chbIngr05.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chbIngr05ActionPerformed(evt);
            }
        });

        chbIngr09.setText("09 Mayonesa: ₡ 50");
        chbIngr09.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chbIngr09ActionPerformed(evt);
            }
        });

        chbIngr08.setText("08 Ketchup: ₡ 50");
        chbIngr08.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chbIngr08ActionPerformed(evt);
            }
        });

        chbIngr19.setText("19 Jamón: ₡ 300");
        chbIngr19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chbIngr19ActionPerformed(evt);
            }
        });

        chbIngr18.setText("18 Tortillas: ₡ 100");
        chbIngr18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chbIngr18ActionPerformed(evt);
            }
        });

        chbIngr10.setText("10 Mantequilla: ₡ 100");
        chbIngr10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chbIngr10ActionPerformed(evt);
            }
        });

        chbIngr11.setText("11 Papas: ₡ 150");
        chbIngr11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chbIngr11ActionPerformed(evt);
            }
        });

        chbIngr12.setText("12 Ajo en polvo: ₡ 15");
        chbIngr12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chbIngr12ActionPerformed(evt);
            }
        });

        chbIngr13.setText("13 Sal: ₡ 5");
        chbIngr13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chbIngr13ActionPerformed(evt);
            }
        });

        chbIngr14.setText("14 Aceite: ₡ 25");
        chbIngr14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chbIngr14ActionPerformed(evt);
            }
        });

        chbIngr15.setText("15 Queso blanco: ₡ 200");
        chbIngr15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chbIngr15ActionPerformed(evt);
            }
        });

        chbIngr16.setText("16 Queso amarillo: ₡ 150");
        chbIngr16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chbIngr16ActionPerformed(evt);
            }
        });

        chbIngr17.setText("17 Pollo: ₡ 400");
        chbIngr17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chbIngr17ActionPerformed(evt);
            }
        });

        lblPrecio.setText("Costo total del producto (suma ingredientes + 25% servicio):");

        btnPrecio.setText("Calcular");
        btnPrecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrecioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout txtNombreLayout = new javax.swing.GroupLayout(txtNombre);
        txtNombre.setLayout(txtNombreLayout);
        txtNombreLayout.setHorizontalGroup(
            txtNombreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(txtNombreLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(txtNombreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(txtNombreLayout.createSequentialGroup()
                        .addGroup(txtNombreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(chbIngr09)
                            .addComponent(chbIngr08)
                            .addComponent(chbIngr07)
                            .addComponent(chbIngr06)
                            .addComponent(chbIngr05)
                            .addComponent(chbIngr04)
                            .addComponent(chbIngr03)
                            .addComponent(chbIngr02)
                            .addComponent(chbIngr01)
                            .addComponent(chbIngr00))
                        .addGap(18, 18, 18)
                        .addGroup(txtNombreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(chbIngr19)
                            .addComponent(chbIngr18)
                            .addComponent(chbIngr17)
                            .addComponent(chbIngr16)
                            .addComponent(chbIngr15)
                            .addComponent(chbIngr14)
                            .addComponent(chbIngr13)
                            .addComponent(chbIngr12)
                            .addComponent(chbIngr11)
                            .addComponent(chbIngr10))
                        .addContainerGap())
                    .addGroup(txtNombreLayout.createSequentialGroup()
                        .addGroup(txtNombreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(txtNombreLayout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txbNombre))
                            .addGroup(txtNombreLayout.createSequentialGroup()
                                .addComponent(lblCrear)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblVolver))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, txtNombreLayout.createSequentialGroup()
                                .addComponent(lblPrecio)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnPrecio, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE))
                            .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, txtNombreLayout.createSequentialGroup()
                                .addGroup(txtNombreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblTitulo, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblExplicacion, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtID, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(18, 18, 18))))
        );
        txtNombreLayout.setVerticalGroup(
            txtNombreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(txtNombreLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblExplicacion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtID)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(txtNombreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txbNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(txtNombreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(txtNombreLayout.createSequentialGroup()
                        .addComponent(chbIngr00)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(chbIngr01)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(chbIngr02)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(chbIngr03)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(chbIngr04)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(chbIngr05)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(chbIngr06)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(chbIngr07)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(chbIngr08)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(chbIngr09))
                    .addGroup(txtNombreLayout.createSequentialGroup()
                        .addComponent(chbIngr10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(chbIngr11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(chbIngr12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(chbIngr13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(chbIngr14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(chbIngr15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(chbIngr16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(chbIngr17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(chbIngr18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(chbIngr19)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(txtNombreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPrecio)
                    .addComponent(btnPrecio))
                .addGap(18, 18, 18)
                .addGroup(txtNombreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCrear)
                    .addComponent(lblVolver))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 402, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 587, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrecioActionPerformed

        AnalizarIngredientes();
        btnPrecio.setText("₡ " + AnalizarPrecio());
    }//GEN-LAST:event_btnPrecioActionPerformed

    private void chbIngr17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chbIngr17ActionPerformed
        btnPrecio.setText("Calcular");
    }//GEN-LAST:event_chbIngr17ActionPerformed

    private void chbIngr16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chbIngr16ActionPerformed
        btnPrecio.setText("Calcular");
    }//GEN-LAST:event_chbIngr16ActionPerformed

    private void chbIngr15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chbIngr15ActionPerformed
        btnPrecio.setText("Calcular");
    }//GEN-LAST:event_chbIngr15ActionPerformed

    private void chbIngr14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chbIngr14ActionPerformed
        btnPrecio.setText("Calcular");
    }//GEN-LAST:event_chbIngr14ActionPerformed

    private void chbIngr13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chbIngr13ActionPerformed
        btnPrecio.setText("Calcular");
    }//GEN-LAST:event_chbIngr13ActionPerformed

    private void chbIngr12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chbIngr12ActionPerformed
        btnPrecio.setText("Calcular");
    }//GEN-LAST:event_chbIngr12ActionPerformed

    private void chbIngr11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chbIngr11ActionPerformed
        btnPrecio.setText("Calcular");
    }//GEN-LAST:event_chbIngr11ActionPerformed

    private void chbIngr10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chbIngr10ActionPerformed
        btnPrecio.setText("Calcular");
    }//GEN-LAST:event_chbIngr10ActionPerformed

    private void chbIngr18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chbIngr18ActionPerformed
        btnPrecio.setText("Calcular");
    }//GEN-LAST:event_chbIngr18ActionPerformed

    private void chbIngr19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chbIngr19ActionPerformed
        btnPrecio.setText("Calcular");
    }//GEN-LAST:event_chbIngr19ActionPerformed

    private void chbIngr08ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chbIngr08ActionPerformed
        btnPrecio.setText("Calcular");
    }//GEN-LAST:event_chbIngr08ActionPerformed

    private void chbIngr09ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chbIngr09ActionPerformed
        btnPrecio.setText("Calcular");
    }//GEN-LAST:event_chbIngr09ActionPerformed

    private void chbIngr05ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chbIngr05ActionPerformed
        btnPrecio.setText("Calcular");
    }//GEN-LAST:event_chbIngr05ActionPerformed

    private void chbIngr04ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chbIngr04ActionPerformed
        btnPrecio.setText("Calcular");
    }//GEN-LAST:event_chbIngr04ActionPerformed

    private void chbIngr06ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chbIngr06ActionPerformed
        btnPrecio.setText("Calcular");
    }//GEN-LAST:event_chbIngr06ActionPerformed

    private void chbIngr07ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chbIngr07ActionPerformed
        btnPrecio.setText("Calcular");
    }//GEN-LAST:event_chbIngr07ActionPerformed

    private void chbIngr02ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chbIngr02ActionPerformed
        btnPrecio.setText("Calcular");
    }//GEN-LAST:event_chbIngr02ActionPerformed

    private void chbIngr03ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chbIngr03ActionPerformed
        btnPrecio.setText("Calcular");
    }//GEN-LAST:event_chbIngr03ActionPerformed

    private void chbIngr01ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chbIngr01ActionPerformed
        btnPrecio.setText("Calcular");
    }//GEN-LAST:event_chbIngr01ActionPerformed

    private void chbIngr00ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chbIngr00ActionPerformed
        btnPrecio.setText("Calcular");
    }//GEN-LAST:event_chbIngr00ActionPerformed

    private void txbNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txbNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txbNombreActionPerformed

    private void lblVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lblVolverActionPerformed

        dispose();
        Tareas tareas = new Tareas(sucursal);
        tareas.setVisible(true);
    }//GEN-LAST:event_lblVolverActionPerformed

    private void lblCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lblCrearActionPerformed

        String nombre = txbNombre.getText();
        AnalizarIngredientes();
        int precio = AnalizarPrecio();
        
        Listas listas = new Listas();
        listas.ObtenerListaProductos().get(editando).setIDProd(ID);
        listas.ObtenerListaProductos().get(editando).setNombre(nombre);
        listas.ObtenerListaProductos().get(editando).setLista(ListarIngredientes());
        listas.ObtenerListaProductos().get(editando).setPrecioProd(precio);
        JOptionPane.showMessageDialog(null, "ID : " + ID + "\nNombre: " + nombre + "\nPrecio: " + precio, " ¡Producto editado!", 1);
        Tareas tareas = new Tareas(sucursal);
        tareas.setVisible(true);
        dispose();
    }//GEN-LAST:event_lblCrearActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditarProducto2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditarProducto2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditarProducto2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditarProducto2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        String Sucursal = "";
        int Editando = 0;
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditarProducto2(Sucursal, Editando).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPrecio;
    private javax.swing.JCheckBox chbIngr00;
    private javax.swing.JCheckBox chbIngr01;
    private javax.swing.JCheckBox chbIngr02;
    private javax.swing.JCheckBox chbIngr03;
    private javax.swing.JCheckBox chbIngr04;
    private javax.swing.JCheckBox chbIngr05;
    private javax.swing.JCheckBox chbIngr06;
    private javax.swing.JCheckBox chbIngr07;
    private javax.swing.JCheckBox chbIngr08;
    private javax.swing.JCheckBox chbIngr09;
    private javax.swing.JCheckBox chbIngr10;
    private javax.swing.JCheckBox chbIngr11;
    private javax.swing.JCheckBox chbIngr12;
    private javax.swing.JCheckBox chbIngr13;
    private javax.swing.JCheckBox chbIngr14;
    private javax.swing.JCheckBox chbIngr15;
    private javax.swing.JCheckBox chbIngr16;
    private javax.swing.JCheckBox chbIngr17;
    private javax.swing.JCheckBox chbIngr18;
    private javax.swing.JCheckBox chbIngr19;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JButton lblCrear;
    private javax.swing.JLabel lblExplicacion;
    private javax.swing.JLabel lblPrecio;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JButton lblVolver;
    private javax.swing.JTextField txbNombre;
    private javax.swing.JLabel txtID;
    private javax.swing.JPanel txtNombre;
    // End of variables declaration//GEN-END:variables
}
