package progra2proy1;

import javax.swing.JOptionPane;

public class VerProducto extends javax.swing.JFrame {

    public String sucursal = "";
    public String ID = "";
    Producto producto = new Producto();

    public VerProducto(String Sucursal) {
        initComponents();
        lblTitulo.setText("Ver producto - " + Sucursal);
        if (Sucursal.equals("San Pedro")) {
            ID = "SP";
        } else if (Sucursal.equals("Los Yoses")) {
            ID = "LY";
        } else {
            ID = "CU";
        }
        GenerarListaProductos();
    }

    public void GenerarListaProductos() {

        String detalle = "";
        Listas listas = new Listas();

        for (int i = 0; i < listas.ObtenerListaProductos().size(); i++) {
            if (listas.ObtenerListaProductos().get(i).getIDProd().startsWith(ID)) {
                detalle = detalle + "ID: " + listas.ObtenerListaProductos().get(i).getIDProd() + " - Nombre: " + listas.ObtenerListaProductos().get(i).getNombre() + "\n";
            }
        }
        txaListado.setText(detalle);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rgrFiltro = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txaListado = new javax.swing.JTextArea();
        lblVolver = new javax.swing.JButton();
        rbtID = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        rbtNombre = new javax.swing.JRadioButton();
        txfFiltro = new javax.swing.JTextField();
        btnVer = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTitulo.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        lblTitulo.setText("Ver producto - SUCURSAL");

        jLabel1.setText("Introduzca el ID o nombre del producto en el cuadro de abajo y haga click");

        jLabel2.setText("en \"Ver detalle\" para obtener toda la información del producto.");

        txaListado.setEditable(false);
        txaListado.setBackground(new java.awt.Color(240, 240, 240));
        txaListado.setColumns(20);
        txaListado.setRows(5);
        txaListado.setBorder(null);
        jScrollPane1.setViewportView(txaListado);

        lblVolver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/progra2proy1/imagenes/volver.png"))); // NOI18N
        lblVolver.setText(" Menú anterior");
        lblVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lblVolverActionPerformed(evt);
            }
        });

        rgrFiltro.add(rbtID);
        rbtID.setSelected(true);
        rbtID.setText(" ID");
        rbtID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtIDActionPerformed(evt);
            }
        });

        jLabel3.setText("Filtrar por:");

        rgrFiltro.add(rbtNombre);
        rbtNombre.setText(" Nombre");

        txfFiltro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txfFiltroActionPerformed(evt);
            }
        });

        btnVer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/progra2proy1/imagenes/search.png"))); // NOI18N
        btnVer.setText("Ver detalle");
        btnVer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblTitulo)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txfFiltro)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(rbtID)
                                            .addComponent(jLabel3)
                                            .addComponent(rbtNombre)
                                            .addComponent(btnVer))
                                        .addGap(0, 0, Short.MAX_VALUE))))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(121, 121, 121)
                        .addComponent(lblVolver)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rbtID)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rbtNombre)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txfFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnVer)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblVolver)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lblVolverActionPerformed

        dispose();
        Tareas tareas = new Tareas(sucursal);
        tareas.setVisible(true);
    }//GEN-LAST:event_lblVolverActionPerformed

    private void rbtIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtIDActionPerformed

    private void btnVerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerActionPerformed

        boolean bandera = false;
        String detalle = "";
        Listas listas = new Listas();

        if (rbtID.isSelected()) {
            for (int i = 0; i < listas.ObtenerListaProductos().size(); i++) {
                if (listas.ObtenerListaProductos().get(i).getIDProd().equalsIgnoreCase(txfFiltro.getText())) {
                    detalle = "El detalle para el ID " + listas.ObtenerListaProductos().get(i).getIDProd()
                            + " es el siguiente:\n\n" + "Nombre: " + listas.ObtenerListaProductos().get(i).getNombre()
                            + "\nPrecio: " + listas.ObtenerListaProductos().get(i).getPrecioProd() + "\n\nLista de ingredientes:\n";
                    bandera = true;
                    for (int j = 0; j < listas.ObtenerListaProductos().get(i).getLista().size(); j++) {
                        detalle = detalle + listas.ObtenerListaProductos().get(i).getLista().get(j).toString();
                    }
                }
            }
        } else if (rbtNombre.isSelected()) {
            for (int i = 0; i < listas.ObtenerListaProductos().size(); i++) {
                if (listas.ObtenerListaProductos().get(i).getNombre().equalsIgnoreCase(txfFiltro.getText())) {
                    detalle = "El detalle para el nombre " + listas.ObtenerListaProductos().get(i).getNombre()
                            + " es el siguiente:\n\n" + "ID: " + listas.ObtenerListaProductos().get(i).getIDProd()
                            + "\nPrecio: " + listas.ObtenerListaProductos().get(i).getPrecioProd() + "\n\nLista de ingredientes:\n";
                    bandera = true;
                    for (int j = 0; j < listas.ObtenerListaProductos().get(i).getLista().size(); j++) {
                        detalle = detalle + listas.ObtenerListaProductos().get(i).getLista().get(j).toString();
                    }
    }//GEN-LAST:event_btnVerActionPerformed
            }
        }

        if (bandera) {
            JOptionPane.showMessageDialog(null, detalle);
        } else {
            JOptionPane.showMessageDialog(null, "No se encuentra el producto especificado");
        }
    }

    private void txfFiltroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txfFiltroActionPerformed

        if (txfFiltro.getText().equals("")) {
            btnVer.setEnabled(false);
        }
    }//GEN-LAST:event_txfFiltroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VerProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VerProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VerProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VerProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        String Sucursal = "";
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VerProducto(Sucursal).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnVer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JButton lblVolver;
    private javax.swing.JRadioButton rbtID;
    private javax.swing.JRadioButton rbtNombre;
    private javax.swing.ButtonGroup rgrFiltro;
    private javax.swing.JTextArea txaListado;
    private javax.swing.JTextField txfFiltro;
    // End of variables declaration//GEN-END:variables
}
